import { useEffect, useState } from 'react'
import { login, register } from './api/auth'
import { clearToken, hasToken } from './api/client'
import { enqueue, pendingCount } from './db/outbox'
import { makeBook, makeEntry, putBook, putEntry, searchLibrary, tombstoneEntry, updateEntry } from './db/library'
import { getSyncStatus, subscribeSync, sync } from './sync/sync'
import type { LibraryItem, ReadingStatus, SyncStatus } from './types'
import { ScanBook } from './components/ScanBook'
import './App.css'

type BookForm = { title: string; author: string; isbn: string; coverUrl: string; readingStatus: ReadingStatus; rating: number; notes: string; dateStarted: string; dateFinished: string }
const serverStatus = (status: ReadingStatus): 'unread' | 'reading' | 'read' => status === 'finished' ? 'read' : status

function AuthScreen({ onAuthenticated }: { onAuthenticated: () => void }) {
  const [mode, setMode] = useState<'login' | 'register'>('login')
  const [identifier, setIdentifier] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { if (mode === 'register') await register(identifier, password); else await login(identifier, password); onAuthenticated() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to authenticate') } finally { setBusy(false) } }
  return <main className="auth-shell"><section className="auth-panel"><span className="eyebrow">FIELD NOTES / LIBRARY</span><h1>{mode === 'register' ? 'Create your shelf.' : 'Welcome back.'}</h1><p className="lede">A quiet, local-first place for the books you are carrying with you.</p><form onSubmit={submit}><label>Email or username<input value={identifier} onChange={(event) => setIdentifier(event.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required minLength={6} /></label>{error && <p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy ? 'Working...' : mode === 'register' ? 'Create account' : 'Sign in'}</button></form><button className="text-button" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'register' ? 'Already have an account? Sign in' : 'New here? Create an account'}</button></section></main>
}

function BookEditor({ item, onSave, onCancel }: { item?: LibraryItem; onSave: (value: BookForm) => void; onCancel: () => void }) {
  const [form, setForm] = useState<BookForm>({ title: item?.book.title ?? '', author: item?.book.author ?? '', isbn: item?.book.isbn ?? '', coverUrl: item?.book.coverUrl ?? '', readingStatus: item?.readingStatus ?? 'unread', rating: item?.rating ?? 0, notes: item?.notes ?? '', dateStarted: item?.dateStarted ?? '', dateFinished: item?.dateFinished ?? '' })
  const update = (key: keyof BookForm, value: string | number) => setForm((current) => ({ ...current, [key]: value }))
  return <form className="editor" onSubmit={(event) => { event.preventDefault(); onSave(form) }}><div className="editor-heading"><span className="eyebrow">{item ? 'EDIT ENTRY' : 'NEW ENTRY'}</span><button type="button" className="close-button" onClick={onCancel}>x</button></div><label>Title<input value={form.title} onChange={(event) => update('title', event.target.value)} required autoFocus readOnly={Boolean(item)} /></label><label>Author<input value={form.author} onChange={(event) => update('author', event.target.value)} required readOnly={Boolean(item)} /></label><div className="two-up"><label>ISBN<input value={form.isbn} onChange={(event) => update('isbn', event.target.value)} readOnly={Boolean(item)} /></label><label>Cover URL<input value={form.coverUrl} onChange={(event) => update('coverUrl', event.target.value)} readOnly={Boolean(item)} /></label></div><div className="two-up"><label>Status<select value={form.readingStatus} onChange={(event) => update('readingStatus', event.target.value)}><option value="unread">Unread</option><option value="reading">Reading</option><option value="finished">Finished</option></select></label><label>Rating<select value={form.rating} onChange={(event) => update('rating', Number(event.target.value))}><option value="0">Not rated</option>{[1, 2, 3, 4, 5].map((rating) => <option key={rating} value={rating}>{rating} / 5</option>)}</select></label></div><div className="two-up"><label>Started<input type="date" value={form.dateStarted} onChange={(event) => update('dateStarted', event.target.value)} /></label><label>Finished<input type="date" value={form.dateFinished} onChange={(event) => update('dateFinished', event.target.value)} /></label></div><label>Notes<textarea value={form.notes} onChange={(event) => update('notes', event.target.value)} rows={3} /></label><div className="form-actions"><button type="button" className="secondary" onClick={onCancel}>Cancel</button><button className="primary">{item ? 'Save changes' : 'Add to library'}</button></div></form>
}

function Library() {
  const [items, setItems] = useState<LibraryItem[]>([]); const [query, setQuery] = useState(''); const [editing, setEditing] = useState<LibraryItem | 'new'>(); const [scanning, setScanning] = useState(false); const [status, setStatus] = useState<SyncStatus>(getSyncStatus())
  async function refresh(nextQuery = query) { const [nextItems, pending] = await Promise.all([searchLibrary(nextQuery), pendingCount()]); setItems(nextItems); setStatus((current) => ({ ...current, pending })) }
  useEffect(() => { void refresh(); void sync(); const unsubscribe = subscribeSync(setStatus); const reconnect = () => void sync(); window.addEventListener('online', reconnect); return () => { unsubscribe(); window.removeEventListener('online', reconnect) } }, [])
  async function save(value: BookForm) { if (editing === 'new') { const book = makeBook(value.title, value.author, { isbn: value.isbn || undefined, coverUrl: value.coverUrl || undefined }); const entry = { ...makeEntry(book.id, value.readingStatus), rating: value.rating || undefined, notes: value.notes || undefined, dateStarted: value.dateStarted || undefined, dateFinished: value.dateFinished || undefined }; await putBook(book); await putEntry(entry); await enqueue({ entityType: 'library_entry', entityId: entry.id, operation: 'create', payload: { isbn13: book.isbn, title: book.title, authors: book.author ? [book.author] : [], cover_url: book.coverUrl, reading_status: serverStatus(entry.readingStatus), rating: entry.rating, notes: entry.notes, date_started: entry.dateStarted, date_finished: entry.dateFinished } }) } else if (editing) { const entry = await updateEntry(editing.id, { readingStatus: value.readingStatus, rating: value.rating || undefined, notes: value.notes || undefined, dateStarted: value.dateStarted || undefined, dateFinished: value.dateFinished || undefined }); const book = { ...editing.book, title: value.title, author: value.author, isbn: value.isbn || undefined, coverUrl: value.coverUrl || undefined, updatedAt: new Date().toISOString() }; await putBook(book); await enqueue({ entityType: 'library_entry', entityId: entry.id, operation: 'update', payload: { reading_status: serverStatus(entry.readingStatus), rating: entry.rating, notes: entry.notes, date_started: entry.dateStarted, date_finished: entry.dateFinished } }) } setEditing(undefined); await refresh() }
  async function remove(item: LibraryItem) { if (!window.confirm(`Remove ${item.book.title} from your library?`)) return; const entry = await tombstoneEntry(item.id); await enqueue({ entityType: 'library_entry', entityId: entry.id, operation: 'delete', payload: {} }); await refresh() }
  const statusLabel = status.state === 'offline' ? 'Offline' : status.state === 'syncing' ? 'Syncing' : status.state === 'error' ? 'Sync error' : status.pending ? `${status.pending} pending` : 'Online / synced'
  return <main className="library-shell"><header className="topbar"><div><span className="eyebrow">PERSONAL LIBRARY</span><h1>Books in orbit</h1></div><div className="top-actions"><span className={`sync-status ${status.state}`}>{statusLabel}</span><button onClick={() => void sync()} disabled={status.state === 'syncing'}>Sync</button><button className="sign-out" onClick={() => { clearToken(); window.location.reload() }}>Sign out</button></div></header>{scanning ? <ScanBook onCancel={() => setScanning(false)} onAdded={() => { setScanning(false); void refresh() }} /> : <><section className="toolbar"><input className="search" placeholder="Search title, author, or ISBN" value={query} onChange={(event) => { setQuery(event.target.value); void refresh(event.target.value) }} /><button className="secondary" onClick={() => setScanning(true)}>Add from Photo</button><button className="primary add-button" onClick={() => setEditing('new')}>Add manually</button></section>{items.length === 0 ? <section className="empty"><p>{query ? 'No books match that search.' : 'Your shelf is still empty.'}</p><button className="text-button" onClick={() => setEditing('new')}>Add your first book</button></section> : <section className="book-list">{items.map((item) => <article className="book-row" key={item.id}><div className="cover">{item.book.coverUrl ? <img src={item.book.coverUrl} alt="" /> : item.book.title.slice(0, 1).toUpperCase()}</div><div className="book-info"><h2>{item.book.title}</h2><p>{item.book.author}</p><div className="meta"><span>{item.readingStatus}</span><span>{item.rating ? `${item.rating} / 5` : 'Not rated'}</span></div></div><div className="row-actions"><button onClick={() => setEditing(item)}>Edit</button><button className="danger" onClick={() => void remove(item)}>Remove</button></div></article>)}</section>}{editing && <div className="modal-backdrop"><BookEditor item={editing === 'new' ? undefined : editing} onSave={save} onCancel={() => setEditing(undefined)} /></div>}</>}</main>
}

export default function App() { const [authenticated, setAuthenticated] = useState(hasToken()); return authenticated ? <Library /> : <AuthScreen onAuthenticated={() => setAuthenticated(true)} /> }
